- platform: powercalc
  entity_id: light.3d_printer_lights
  unique_id: powercalc_light_3d_printer_lights
- platform: powercalc
  entity_id: light.alcove_lights
  unique_id: powercalc_light_alcove_lights
- platform: powercalc
  entity_id: light.bathroom
  unique_id: powercalc_light_bathroom
- platform: powercalc
  entity_id: light.bedroom
  unique_id: powercalc_light_bedroom
- platform: powercalc
  entity_id: light.bedroom_diffuser
  unique_id: powercalc_light_bedroom_diffuser
- platform: powercalc
  entity_id: light.bedroom_door_bedside_light
  unique_id: powercalc_light_bedroom_door_bedside_light
- platform: powercalc
  entity_id: light.bedroom_overhead
  unique_id: powercalc_light_bedroom_overhead
- platform: powercalc
  entity_id: light.bedroom_window_bedside_light
  unique_id: powercalc_light_bedroom_window_bedside_light
- platform: powercalc
  entity_id: light.bedside
  unique_id: powercalc_lightgroup__bedside
- platform: powercalc
  entity_id: light.bookcase_light
  unique_id: powercalc_light_bookcase_light
- platform: powercalc
  entity_id: light.christmas_star_lights
  unique_id: powercalc_light_christmas_star_lights
- platform: powercalc
  entity_id: light.christmas_tree
  unique_id: powercalc_light_christmas_tree
- platform: powercalc
  entity_id: light.go
  unique_id: powercalc_light_go
- platform: powercalc
  entity_id: light.hallway
  unique_id: powercalc_light_hallway
- platform: powercalc
  entity_id: light.hallway_overhead
  unique_id: powercalc_light_hallway_overhead
- platform: powercalc
  entity_id: light.hue_play_left
  unique_id: powercalc_light_hue_play_left
- platform: powercalc
  entity_id: light.hue_play_right
  unique_id: powercalc_light_hue_play_right
- platform: powercalc
  entity_id: light.iris
  unique_id: powercalc_light_iris
- platform: powercalc
  entity_id: light.kitchen
  unique_id: powercalc_light_kitchen
- platform: powercalc
  entity_id: light.lava_lamp
  unique_id: powercalc_light_lava_lamp
- platform: powercalc
  entity_id: light.light_panels
  unique_id: powercalc_light_light_panels
- platform: powercalc
  entity_id: light.living_room
  unique_id: powercalc_light_living_room
- platform: powercalc
  entity_id: light.living_room_2
  unique_id: powercalc_light_living_room_2
- platform: powercalc
  entity_id: light.living_room_diffuser
  unique_id: powercalc_light_living_room_diffuser
- platform: powercalc
  entity_id: light.living_room_kitchen
  unique_id: powercalc_light_living_room_kitchen
- platform: powercalc
  entity_id: light.living_room_main_lights
  unique_id: powercalc_lightgroup__living_room_main_lights
- platform: powercalc
  entity_id: light.living_room_overhead
  unique_id: powercalc_lightgroup__living_room_overhead
- platform: powercalc
  entity_id: light.living_room_patio
  unique_id: powercalc_light_living_room_patio
- platform: powercalc
  entity_id: light.office
  unique_id: powercalc_light_office
- platform: powercalc
  entity_id: light.office_diffuser
  unique_id: powercalc_light_office_diffuser
- platform: powercalc
  entity_id: light.office_overhead
  unique_id: powercalc_light_office_overhead
- platform: powercalc
  entity_id: light.philips_tv
  unique_id: powercalc_light_philips_tv
- platform: powercalc
  entity_id: light.reading_light
  unique_id: powercalc_light_reading_light
- platform: powercalc
  entity_id: light.shelf_lights
  unique_id: powercalc_light_shelf_lights
- platform: powercalc
  entity_id: light.smart_star_projector
  unique_id: powercalc_light_smart_star_projector
- platform: powercalc
  entity_id: light.television
  unique_id: powercalc_light_television
- platform: powercalc
  entity_id: light.under_bed_lights
  unique_id: powercalc_light_under_bed_lights
- platform: powercalc
  entity_id: light.uplighter
  unique_id: powercalc_light_uplighter
- platform: powercalc
  entity_id: light.wake_up
  unique_id: powercalc_lightgroup__wake_up
- platform: powercalc
  entity_id: light.wardrobe_lights
  unique_id: powercalc_light_wardrobe_lights
- platform: powercalc
  entity_id: switch.100126c872_1
  unique_id: powercalc_switch_100126c872_1
- platform: powercalc
  entity_id: switch.100126cbba_1
  unique_id: powercalc_switch_100126cbba_1
- platform: powercalc
  entity_id: switch.100126cbfc_1
  unique_id: powercalc_switch_100126cbfc_1
- platform: powercalc
  entity_id: switch.10012c724d_1
  unique_id: powercalc_switch_10012c724d_1
- platform: powercalc
  entity_id: switch.3d_print_cam_audio_recording
  unique_id: powercalc_switch_3d_print_cam_audio_recording
- platform: powercalc
  entity_id: switch.3d_print_cam_auto_night_vision
  unique_id: powercalc_switch_3d_print_cam_auto_night_vision
- platform: powercalc
  entity_id: switch.3d_print_cam_enabled
  unique_id: powercalc_switch_3d_print_cam_enabled
- platform: powercalc
  entity_id: switch.3d_print_cam_microphone
  unique_id: powercalc_switch_3d_print_cam_microphone
- platform: powercalc
  entity_id: switch.3d_print_cam_motion_detection
  unique_id: powercalc_switch_3d_print_cam_motion_detection
- platform: powercalc
  entity_id: switch.3d_print_cam_motion_tracking
  unique_id: powercalc_switch_3d_print_cam_motion_tracking
- platform: powercalc
  entity_id: switch.3d_print_cam_pet_detection
  unique_id: powercalc_switch_3d_print_cam_pet_detection
- platform: powercalc
  entity_id: switch.3d_print_cam_rtsp_stream
  unique_id: powercalc_switch_3d_print_cam_rtsp_stream
- platform: powercalc
  entity_id: switch.3d_print_cam_sound_detection
  unique_id: powercalc_switch_3d_print_cam_sound_detection
- platform: powercalc
  entity_id: switch.3d_print_cam_speaker
  unique_id: powercalc_switch_3d_print_cam_speaker
- platform: powercalc
  entity_id: switch.3d_print_cam_status_led
  unique_id: powercalc_switch_3d_print_cam_status_led
- platform: powercalc
  entity_id: switch.3d_printer_monitor
  unique_id: powercalc_switch_3d_printer_monitor
- platform: powercalc
  entity_id: switch.43pus8505_12_ambilight_hue
  unique_id: powercalc_switch_43pus8505_12_ambilight_hue
- platform: powercalc
  entity_id: switch.43pus8505_12_screen_state
  unique_id: powercalc_switch_43pus8505_12_screen_state
- platform: powercalc
  entity_id: switch.adaptive_lighting_adapt_brightness_office_overhead
  unique_id: powercalc_switch_adaptive_lighting_adapt_brightness_office_overhead
- platform: powercalc
  entity_id: switch.adaptive_lighting_adapt_color_office_overhead
  unique_id: powercalc_switch_adaptive_lighting_adapt_color_office_overhead
- platform: powercalc
  entity_id: switch.adaptive_lighting_office_overhead
  unique_id: powercalc_switch_adaptive_lighting_office_overhead
- platform: powercalc
  entity_id: switch.adaptive_lighting_sleep_mode_office_overhead
  unique_id: powercalc_switch_adaptive_lighting_sleep_mode_office_overhead
- platform: powercalc
  entity_id: switch.bathroom_light
  unique_id: powercalc_switch_bathroom_light
- platform: powercalc
  entity_id: switch.bedroom_air_freshener
  unique_id: powercalc_switch_bedroom_air_freshener
- platform: powercalc
  entity_id: switch.bedroom_air_purifier_filter_cartridge_reset
  unique_id: powercalc_switch_bedroom_air_purifier_filter_cartridge_reset
- platform: powercalc
  entity_id: switch.bedroom_air_purifier_power
  unique_id: powercalc_switch_bedroom_air_purifier_power
- platform: powercalc
  entity_id: switch.bedroom_heater
  unique_id: powercalc_switch_bedroom_heater
- platform: powercalc
  entity_id: switch.bedroom_sensor_illuminance
  unique_id: powercalc_switch_bedroom_sensor_illuminance
- platform: powercalc
  entity_id: switch.bedroom_sensor_motion
  unique_id: powercalc_switch_bedroom_sensor_motion
- platform: powercalc
  entity_id: switch.buttercup_advanced_mode
  unique_id: powercalc_switch_buttercup_advanced_mode
- platform: powercalc
  entity_id: switch.buttercup_carpet_auto_fan_speed_boost
  unique_id: powercalc_switch_buttercup_carpet_auto_fan_speed_boost
- platform: powercalc
  entity_id: switch.buttercup_continuous_cleaning
  unique_id: powercalc_switch_buttercup_continuous_cleaning
- platform: powercalc
  entity_id: switch.christmas_extension_lead_led
  unique_id: powercalc_switch_christmas_extension_lead_led
- platform: powercalc
  entity_id: switch.christmas_star_lights
  unique_id: powercalc_switch_christmas_star_lights
- platform: powercalc
  entity_id: switch.christmas_tree
  unique_id: powercalc_switch_christmas_tree
- platform: powercalc
  entity_id: switch.dishwasher_monitor
  unique_id: powercalc_switch_dishwasher_monitor
- platform: powercalc
  entity_id: switch.dishwasher_monitor_led
  unique_id: powercalc_switch_dishwasher_monitor_led
- platform: powercalc
  entity_id: switch.electric_blanket
  unique_id: powercalc_switchgroup__electric_blanket
- platform: powercalc
  entity_id: switch.electric_blanket_left
  unique_id: powercalc_switch_electric_blanket_left
- platform: powercalc
  entity_id: switch.electric_blanket_right
  unique_id: powercalc_switch_electric_blanket_right
- platform: powercalc
  entity_id: switch.entryway_camera_audio_recording
  unique_id: powercalc_switch_entryway_camera_audio_recording
- platform: powercalc
  entity_id: switch.entryway_camera_auto_night_vision
  unique_id: powercalc_switch_entryway_camera_auto_night_vision
- platform: powercalc
  entity_id: switch.entryway_camera_enabled
  unique_id: powercalc_switch_entryway_camera_enabled
- platform: powercalc
  entity_id: switch.entryway_camera_microphone
  unique_id: powercalc_switch_entryway_camera_microphone
- platform: powercalc
  entity_id: switch.entryway_camera_motion_detection
  unique_id: powercalc_switch_entryway_camera_motion_detection
- platform: powercalc
  entity_id: switch.entryway_camera_motion_tracking
  unique_id: powercalc_switch_entryway_camera_motion_tracking
- platform: powercalc
  entity_id: switch.entryway_camera_pet_detection
  unique_id: powercalc_switch_entryway_camera_pet_detection
- platform: powercalc
  entity_id: switch.entryway_camera_rtsp_stream
  unique_id: powercalc_switch_entryway_camera_rtsp_stream
- platform: powercalc
  entity_id: switch.entryway_camera_sound_detection
  unique_id: powercalc_switch_entryway_camera_sound_detection
- platform: powercalc
  entity_id: switch.entryway_camera_speaker
  unique_id: powercalc_switch_entryway_camera_speaker
- platform: powercalc
  entity_id: switch.entryway_camera_status_led
  unique_id: powercalc_switch_entryway_camera_status_led
- platform: powercalc
  entity_id: switch.harmony_hub_my_apple_tv
  unique_id: powercalc_switch_harmony_hub_my_apple_tv
- platform: powercalc
  entity_id: switch.harmony_hub_switch
  unique_id: powercalc_switch_harmony_hub_switch
- platform: powercalc
  entity_id: switch.harmony_hub_watch_tv
  unique_id: powercalc_switch_harmony_hub_watch_tv
- platform: powercalc
  entity_id: switch.harmony_hub_wii
  unique_id: powercalc_switch_harmony_hub_wii
- platform: powercalc
  entity_id: switch.kitchen_camera_audio_recording
  unique_id: powercalc_switch_kitchen_camera_audio_recording
- platform: powercalc
  entity_id: switch.kitchen_camera_auto_night_vision
  unique_id: powercalc_switch_kitchen_camera_auto_night_vision
- platform: powercalc
  entity_id: switch.kitchen_camera_enabled
  unique_id: powercalc_switch_kitchen_camera_enabled
- platform: powercalc
  entity_id: switch.kitchen_camera_microphone
  unique_id: powercalc_switch_kitchen_camera_microphone
- platform: powercalc
  entity_id: switch.kitchen_camera_motion_detection
  unique_id: powercalc_switch_kitchen_camera_motion_detection
- platform: powercalc
  entity_id: switch.kitchen_camera_pet_detection
  unique_id: powercalc_switch_kitchen_camera_pet_detection
- platform: powercalc
  entity_id: switch.kitchen_camera_rtsp_stream
  unique_id: powercalc_switch_kitchen_camera_rtsp_stream
- platform: powercalc
  entity_id: switch.kitchen_camera_sound_detection
  unique_id: powercalc_switch_kitchen_camera_sound_detection
- platform: powercalc
  entity_id: switch.kitchen_camera_speaker
  unique_id: powercalc_switch_kitchen_camera_speaker
- platform: powercalc
  entity_id: switch.kitchen_camera_status_led
  unique_id: powercalc_switch_kitchen_camera_status_led
- platform: powercalc
  entity_id: switch.kitchen_light_switch
  unique_id: powercalc_switch_kitchen_light_switch
- platform: powercalc
  entity_id: switch.lava_lamp
  unique_id: powercalc_switch_lava_lamp
- platform: powercalc
  entity_id: switch.living_room_air_freshener
  unique_id: powercalc_switch_living_room_air_freshener
- platform: powercalc
  entity_id: switch.living_room_air_freshener_2
  unique_id: powercalc_switch_living_room_air_freshener_2
- platform: powercalc
  entity_id: switch.living_room_camera_audio_recording
  unique_id: powercalc_switch_living_room_camera_audio_recording
- platform: powercalc
  entity_id: switch.living_room_camera_auto_night_vision
  unique_id: powercalc_switch_living_room_camera_auto_night_vision
- platform: powercalc
  entity_id: switch.living_room_camera_enabled
  unique_id: powercalc_switch_living_room_camera_enabled
- platform: powercalc
  entity_id: switch.living_room_camera_microphone
  unique_id: powercalc_switch_living_room_camera_microphone
- platform: powercalc
  entity_id: switch.living_room_camera_motion_detection
  unique_id: powercalc_switch_living_room_camera_motion_detection
- platform: powercalc
  entity_id: switch.living_room_camera_motion_tracking
  unique_id: powercalc_switch_living_room_camera_motion_tracking
- platform: powercalc
  entity_id: switch.living_room_camera_pet_detection
  unique_id: powercalc_switch_living_room_camera_pet_detection
- platform: powercalc
  entity_id: switch.living_room_camera_rtsp_stream
  unique_id: powercalc_switch_living_room_camera_rtsp_stream
- platform: powercalc
  entity_id: switch.living_room_camera_sound_detection
  unique_id: powercalc_switch_living_room_camera_sound_detection
- platform: powercalc
  entity_id: switch.living_room_camera_speaker
  unique_id: powercalc_switch_living_room_camera_speaker
- platform: powercalc
  entity_id: switch.living_room_camera_status_led
  unique_id: powercalc_switch_living_room_camera_status_led
- platform: powercalc
  entity_id: switch.living_room_heating_pad
  unique_id: powercalc_switch_living_room_heating_pad
- platform: powercalc
  entity_id: switch.lounge_sensor_illuminance
  unique_id: powercalc_switch_lounge_sensor_illuminance
- platform: powercalc
  entity_id: switch.lounge_sensor_motion
  unique_id: powercalc_switch_lounge_sensor_motion
- platform: powercalc
  entity_id: switch.mac_studio
  unique_id: powercalc_switch_mac_studio
- platform: powercalc
  entity_id: switch.microwave
  unique_id: powercalc_switch_microwave
- platform: powercalc
  entity_id: switch.office_air_purifier_filter_cartridge_reset
  unique_id: powercalc_switch_office_air_purifier_filter_cartridge_reset
- platform: powercalc
  entity_id: switch.office_air_purifier_power
  unique_id: powercalc_switch_office_air_purifier_power
- platform: powercalc
  entity_id: switch.office_heater
  unique_id: powercalc_switch_office_heater
- platform: powercalc
  entity_id: switch.office_heating_pad
  unique_id: powercalc_switch_office_heating_pad
- platform: powercalc
  entity_id: switch.office_sensor_illuminance
  unique_id: powercalc_switch_office_sensor_illuminance
- platform: powercalc
  entity_id: switch.office_sensor_motion
  unique_id: powercalc_switch_office_sensor_motion
- platform: powercalc
  entity_id: switch.rf_controller
  unique_id: powercalc_switch_rf_controller
- platform: powercalc
  entity_id: switch.shredder_monitor
  unique_id: powercalc_switch_shredder_monitor
- platform: powercalc
  entity_id: switch.shredder_monitor_led
  unique_id: powercalc_switch_shredder_monitor_led
- platform: powercalc
  entity_id: switch.shredder_monitor_led_2
  unique_id: powercalc_switch_shredder_monitor_led_2
- platform: powercalc
  entity_id: switch.smartmi_air_purifier_p1_power
  unique_id: powercalc_switch_smartmi_air_purifier_p1_power
- platform: powercalc
  entity_id: switch.smoke_detector_alarm
  unique_id: powercalc_switch_smoke_detector_alarm
- platform: powercalc
  entity_id: switch.smoke_detector_silence_siren
  unique_id: powercalc_switch_smoke_detector_silence_siren
- platform: powercalc
  entity_id: switch.smoke_detector_test_alarm
  unique_id: powercalc_switch_smoke_detector_test_alarm
- platform: powercalc
  entity_id: switch.sonos_roam_loudness
  unique_id: powercalc_switch_sonos_roam_loudness
- platform: powercalc
  entity_id: switch.sonos_sonos_roam_crossfade
  unique_id: powercalc_switch_sonos_sonos_roam_crossfade
- platform: powercalc
  entity_id: switch.sonos_sonos_roam_status_light
  unique_id: powercalc_switch_sonos_sonos_roam_status_light
- platform: powercalc
  entity_id: switch.sonos_sonos_roam_touch_controls
  unique_id: powercalc_switch_sonos_sonos_roam_touch_controls
- platform: powercalc
  entity_id: switch.sonos_wall_art_crossfade
  unique_id: powercalc_switch_sonos_wall_art_crossfade
- platform: powercalc
  entity_id: switch.sonos_wall_art_status_light
  unique_id: powercalc_switch_sonos_wall_art_status_light
- platform: powercalc
  entity_id: switch.sonos_wall_art_touch_controls
  unique_id: powercalc_switch_sonos_wall_art_touch_controls
- platform: powercalc
  entity_id: switch.storage_cupboard_camera_anti_theft_detection
  unique_id: powercalc_switch_storage_cupboard_camera_anti_theft_detection
- platform: powercalc
  entity_id: switch.storage_cupboard_camera_audio_recording
  unique_id: powercalc_switch_storage_cupboard_camera_audio_recording
- platform: powercalc
  entity_id: switch.storage_cupboard_camera_enabled
  unique_id: powercalc_switch_storage_cupboard_camera_enabled
- platform: powercalc
  entity_id: switch.storage_cupboard_camera_light
  unique_id: powercalc_switch_storage_cupboard_camera_light
- platform: powercalc
  entity_id: switch.storage_cupboard_camera_microphone
  unique_id: powercalc_switch_storage_cupboard_camera_microphone
- platform: powercalc
  entity_id: switch.storage_cupboard_camera_motion_detection
  unique_id: powercalc_switch_storage_cupboard_camera_motion_detection
- platform: powercalc
  entity_id: switch.storage_cupboard_camera_night_vision
  unique_id: powercalc_switch_storage_cupboard_camera_night_vision
- platform: powercalc
  entity_id: switch.storage_cupboard_camera_rtsp_stream
  unique_id: powercalc_switch_storage_cupboard_camera_rtsp_stream
- platform: powercalc
  entity_id: switch.storage_cupboard_camera_speaker
  unique_id: powercalc_switch_storage_cupboard_camera_speaker
- platform: powercalc
  entity_id: switch.storage_cupboard_camera_status_led
  unique_id: powercalc_switch_storage_cupboard_camera_status_led
- platform: powercalc
  entity_id: switch.timeguard_time_switch_e7b0d48a_advance_mode
  unique_id: powercalc_switch_timeguard_time_switch_e7b0d48a_advance_mode
- platform: powercalc
  entity_id: switch.tradfri_outlet_2
  unique_id: powercalc_switch_tradfri_outlet_2
- platform: powercalc
  entity_id: switch.tumble_dryer_monitor
  unique_id: powercalc_switch_tumble_dryer_monitor
- platform: powercalc
  entity_id: switch.tumble_dryer_monitor_led
  unique_id: powercalc_switch_tumble_dryer_monitor_led
- platform: powercalc
  entity_id: switch.virtual_hallway_heater_virtual
  unique_id: powercalc_switch_virtual_hallway_heater_virtual
- platform: powercalc
  entity_id: switch.virtual_living_room_heater_virtual
  unique_id: powercalc_switch_virtual_living_room_heater_virtual
- platform: powercalc
  entity_id: switch.wall_art_loudness
  unique_id: powercalc_switch_wall_art_loudness
- platform: powercalc
  entity_id: switch.washing_machine_monitor
  unique_id: powercalc_switch_washing_machine_monitor
- platform: powercalc
  entity_id: switch.washing_machine_monitor_led
  unique_id: powercalc_switch_washing_machine_monitor_led
- platform: powercalc
  entity_id: switch.xiaomi_airfryer_mi_smart_air_fryer_3_5l
  unique_id: powercalc_switch_xiaomi_airfryer_mi_smart_air_fryer_3_5l